---

env:
  node: true
  jest/globals: true

extends:
- airbnb-base
- 'plugin:jest/recommended'

parser: babel-eslint

plugins:
- jest

rules:
  "linebreak-style": 0
  "comma-dangle": 0
  "no-underscore-dangle": 0
